build:
  publish: ./build
  environment:
    NODE_ENV: production
  commands:
    - npm run build # لتجميع المشروع قبل النشر

static_sites:
  - route: "/"
    dest: "/index.html"
  - route: "/dashboard"
    dest: "/index.html"
  - route: "/login"
    dest: "/index.html"
  - route: "/registration"
    dest: "/index.html"
  - route: "/transactions/selling"
    dest: "/index.html"
  - route: "/transactions/input"
    dest: "/index.html"
  - route: "/transactions/output"
    dest: "/index.html"
  - route: "/transactions/recharge"
    dest: "/index.html"
  - route: "/transactions/maintenance"
    dest: "/index.html"
  - route: "/transactions/customer_payment"
    dest: "/index.html"
  - route: "/transactions/supplier_payment"
    dest: "/index.html"
  - route: "/transactions/purchasing"
    dest: "/index.html"
  - route: "/transactions/returns"
    dest: "/index.html"
  - route: "/transactions/output_staff"
    dest: "/index.html"
  - route: "/transactions/warranty"
    dest: "/index.html"
  - route: "/inventory"
    dest: "/index.html"
  - route: "/checkout"
    dest: "/index.html"
  - route: "/order-receipt/:orderId"
    dest: "/index.html"
  - route: "/all-orders"
    dest: "/index.html"
  - route: "/all-products"
    dest: "/index.html"
  - route: "/edit-product/:barcode"
    dest: "/index.html"
  - route: "/all-transactions"
    dest: "/index.html"
  - route: "/sales"
    dest: "/index.html"
  - route: "/suppliers"
    dest: "/index.html"
  - route: "/customers"
    dest: "/index.html"
  - route: "/reports"
    dest: "/index.html"
  - route: "/reports/salesReport"
    dest: "/index.html"
  - route: "/all-sales-reports"
    dest: "/index.html"
  - route: "/reports/revenueReport"
    dest: "/index.html"
  - route: "/all-revenue-reports"
    dest: "/index.html"
  - route: "/revenue-report/:reportId"
    dest: "/index.html"
  - route: "/reports/bestSellerReport"
    dest: "/index.html"
  - route: "/reports/stockReport"
    dest: "/index.html"
  - route: "/transactions/bank"
    dest: "/index.html"
